feign:
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200  # 最大的连接数
    max-connections-per-route: 50  # 每个路径的最大连接数
spring:
  application:
    name: eureka-client
eureka:
  instance:
    instance-id: eureka-client # 修改 Eureka上的默认描述信息
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/